# Generated by Django 4.0.5 on 2022-06-13 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
